[package]
name = "Namespace-testing"
version = "0.1.0"
authors = ["M:Munier <marc@geomaps.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="*"