name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'true'
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Build AFL/QEMU
      run: sudo apt-get install protobuf protobuf-c protobuf-c-devel protobuf-compiler protobuf-devel protobuf-python && make
    - name: Build Rust
      run: cargo build --verbose

    - name: Install criu
      run: sudo apt-get install --no-install-recommends criu
    - name: Run criu service
      run: sudo criu service -v4 --address /tmp/criu_service.socket &> /tmp/criu.out &
    - name: Run tests
      run: cargo test --verbose
